# Generated by Django 2.2.24 on 2023-07-05 20:23

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(full_name=flat.owner,
                                    phonenumber=flat.owners_phonenumber,
                                    pure_phone=flat.owner_pure_phone,)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20230705_2318'),
    ]

    operations = [
        migrations.RunPython(fill_owners)
    ]
