# Generated by Django 2.2.24 on 2023-07-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230705_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ManyToManyField(related_name='owner_flats', to='property.Owner', verbose_name='Владелец'),
        ),
    ]
