# Generated by Django 2.2.24 on 2023-07-05 12:59

from django.db import migrations

def fill_db_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        owner = Owner.objects.get(full_name=flat.owner_deprecated,
                          phonenumber=flat.owners_phonenumber,
                          pure_phone=flat.owner_pure_phone,)
        flat.owner.add(owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_flat_owner'),
    ]

    operations = [
        migrations.RunPython(fill_db_owners)
    ]
